######################## default configuration ####################
baseURL = "https://sharp-gates-538d88.netlify.app"
languageCode = "en-us"
title = "Comprar una guitarra"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Guitarras"
  URL = "mi-primera-guitarra"
  weight = 1

  # main menu
  [[menu.main]]
  name = "Accesorios"
  URL = "accesorios"
  weight = 2

  # footer menu
  [[menu.footer]]
  name = "Aviso legal"
  URL = "aviso-legal"
  weight = 1
  
  [[menu.footer]]
  name = "Política de privacidad"
  URL = "politica-de-privacidad"
  weight = 2

  [[menu.footer]]
  name = "Uso de cookies"
  URL = "uso-de-cookies"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "UA-166363107-1"
# copyright
copyright = "| copyright &copy; 2020 [Comprar una Guitarra](https://www.comprarunaguitarra.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true