######################## default configuration ####################
baseURL = "https://www.comprarunaguitarra.com/"
languageCode = "es-ES"
title = "Guitarras eléctricas | Guia para comprar una guitarra eléctrica"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Guitarras"
  hasChildren = true
  weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras baratas"
    parent = "Guitarras"
    URL = "guitarras-baratas/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas para niños"
    parent = "Guitarras"
    URL = "guitarras-electricas-niños/"
    weight = 2

  # main menu
  [[menu.main]]
  name = "Marcas"
  hasChildren = true
  weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Yamaha"
    parent = "Marcas"
    URL = "guitarras-yamaha/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras LTD ESP"
    parent = "Marcas"
    URL = "guitarras-ltd/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Squier"
    parent = "Marcas"
    URL = "guitarras-squier/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras Cort"
    parent = "Marcas"
    URL = "guitarras-cort/"
    weight = 4


  # main menu
  [[menu.main]]
  name = "Accesorios"
  hasChildren = true
  weight = 3
    # main menu
    [[menu.main]]
    name = "Behringer Guitar Link"
    parent = "Accesorios"
    URL = "behringer-guitar-link/"
    weight = 1

  # footer menu
  [[menu.footer]]
  name = "Aviso legal"
  URL = "aviso-legal"
  weight = 1
  
  [[menu.footer]]
  name = "Política de privacidad"
  URL = "politica-de-privacidad"
  weight = 2

  [[menu.footer]]
  name = "Uso de cookies"
  URL = "uso-de-cookies"
  weight = 3
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "sitemap"
  weight = 4
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo_web_opt_2.png"
home = "Inicio"
# Meta data
description = "Encuentra y compra la guitarra eléctrica perfecta para ti. Consulta y compara diferentes modelos y marcas conocidas como Yamaha, LTD, Ibanez, Fender Squier o Cort."
author = "Comprar una Guitarra"
# Google Analitycs
googleAnalitycsID = "UA-167226734-1"
# copyright
copyright = "| copyright &copy; 2020 [Comprar una Guitarra](/) All Rights Reserved |"