######################## default configuration ####################
baseURL = "https://www.comprarunaguitarra.com/"
languageCode = "es"
title = "Consejos y reviews sobre que guitarra comprar en 2021"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  
############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Las mejores"
  hasChildren = true
  weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas baratas"
    parent = "Las mejores"
    URL = "guitarras-electricas-baratas/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas para niños"
    parent = "Las mejores"
    URL = "guitarras-para-ninos/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras en miniatura"
    parent = "Las mejores"
    URL = "guitarras-en-miniatura/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras pequeñas de cuatro cuerdas y ukeleles"
    parent = "Las mejores"
    URL = "guitarra-pequena-cuatro-cuerdas/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Guitarras musicales"
    parent = "Las mejores"
    URL = "guitarras-musicales/"
    weight = 5

  # main menu
  [[menu.main]]
  name = "Marcas"
  hasChildren = true
  weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Cort"
    parent = "Marcas"
    URL = "guitarras-cort/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras Epiphone"
    parent = "Marcas"
    URL = "guitarras-epiphone/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Ibanez"
    parent = "Marcas"
    URL = "guitarras-ibanez/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras LTD ESP"
    parent = "Marcas"
    URL = "guitarras-ltd/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Guitarras Squier"
    parent = "Marcas"
    URL = "guitarras-squier/"
    weight = 5
    # main menu
    [[menu.main]]
    name = "Guitarras Yamaha"
    parent = "Marcas"
    URL = "guitarras-yamaha/"
    weight = 6
    
   # main menu
  [[menu.main]]
  name = "Accesorios"
  hasChildren = true
  weight = 3
    # main menu
    [[menu.main]]
    name = "Afinador de guitarra"
    parent = "Accesorios"
    URL = "afinador-de-guitarra/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Behringer Guitar Link"
    parent = "Accesorios"
    URL = "behringer-guitar-link/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Inlays para guitarra"
    parent = "Accesorios"
    URL = "inlays-guitarra/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Micrófonos de condensador"
    parent = "Accesorios"
    URL = "microfonos-de-condensador"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Pastillas para guitarra"
    parent = "Accesorios"
    URL = "pastillas-para-guitarra/"
    weight = 5
    [[menu.main]]
    name = "Puas de guitarra"
    parent = "Accesorios"
    URL = "puas-guitarra/"
    weight = 6
    # main menu
    [[menu.main]]
    name = "Transmisores inalámbricos"
    parent = "Accesorios"
    URL = "transmisores-inalambricos-guitarra/"
    weight = 7
    
    # main menu
    [[menu.main]]
    name = "Guitarristas"
    hasChildren = true
    weight = 4
    # main menu
    #[[menu.main]]
    #name = "Carlos Santana"
    #parent = "Guitarristas"
    #URL = "carlos-santana/"
    #weight = 1
    # main menu
    [[menu.main]]
    name = "Daron Malakian"
    parent = "Guitarristas"
    URL = "daron-malakian/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Eddie Van Halen"
    parent = "Guitarristas"
    URL = "eddie-van-halen/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "James Hetfield"
    parent = "Guitarristas"
    URL = "james-hetfield/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Kirk Hammett"
    parent = "Guitarristas"
    URL = "kirk-hammett/"
    weight = 5
    # main menu
    [[menu.main]]
    name = "Slash"
    parent = "Guitarristas"
    URL = "slash/"
    weight = 6
    
    [[menu.main]]
	  name = "Blog"
	  URL = "blog"
	  weight = 5

  # footer menu
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "mapa-web"
  weight = 1
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/comprar-una-guitarra.png"
home = "Inicio"
# Meta data
description = "Aquí podrás encontrar reviews, comparativas, consejos, tutoriales y noticias acerca del mundo de la guitarra y otros accesorios relacionados con la música"
author = "CuG"
# Google Analitycs
googleAnalitycsID = "UA-167226734-1"
# copyright
copyright = "| Copyright (c) 2020 Themefisher |"

# Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = false
expire_days = 60


############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/ComprarUna"