######################## default configuration ####################
baseURL = "https://www.comprarunaguitarra.com/"
languageCode = "es"
title = "Consejos y reviews sobre que guitarra comprar en 2020"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Guitarras"
  hasChildren = true
  weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas baratas"
    parent = "Guitarras"
    URL = "guitarras-electricas-baratas/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas para niños"
    parent = "Guitarras"
    URL = "guitarras-para-ninos/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras en miniatura"
    parent = "Guitarras"
    URL = "guitarras-en-miniatura/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras pequeñas de cuatro cuerdas y ukeleles"
    parent = "Guitarras"
    URL = "guitarra-pequena-cuatro-cuerdas/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Guitarras musicales"
    parent = "Guitarras"
    URL = "guitarras-musicales/"
    weight = 5

  # main menu
  [[menu.main]]
  name = "Marcas"
  hasChildren = true
  weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Cort"
    parent = "Marcas"
    URL = "guitarras-cort/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras Epiphone"
    parent = "Marcas"
    URL = "guitarras-epiphone/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras LTD ESP"
    parent = "Marcas"
    URL = "ltd/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras Squier"
    parent = "Marcas"
    URL = "guitarras-squier/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Guitarras Yamaha"
    parent = "Marcas"
    URL = "guitarras-yamaha/"
    weight = 5

  # main menu
  [[menu.main]]
  name = "Accesorios"
  hasChildren = true
  weight = 3
    # main menu
    [[menu.main]]
    name = "Behringer Guitar Link"
    parent = "Accesorios"
    URL = "behringer-guitar-link/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Inlays para guitarra"
    parent = "Accesorios"
    URL = "inlays-guitarra/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Micrófonos de condensador"
    parent = "Accesorios"
    URL = "microfonos-de-condensador"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Pastillas para guitarra"
    parent = "Accesorios"
    URL = "pastillas-para-guitarra/"
    weight = 4
    [[menu.main]]
    name = "Puas de guitarra"
    parent = "Accesorios"
    URL = "puas-guitarra/"
    weight = 5
    # main menu
    [[menu.main]]
    name = "Transmisores inalámbricos"
    parent = "Accesorios"
    URL = "transmisores-inalambricos-guitarra/"
    weight = 6

  # main menu
    [[menu.main]]
    name = "Guitarristas"
    hasChildren = true
    weight = 4
    # main menu
    [[menu.main]]
    name = "Daron Malakian"
    parent = "Guitarristas"
    URL = "daron-malakian/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Eddie Van Halen"
    parent = "Guitarristas"
    URL = "eddie-van-halen/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "James Hetfield"
    parent = "Guitarristas"
    URL = "james-hetfield/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Kirk Hammett"
    parent = "Guitarristas"
    URL = "kirk-hammett/"
    weight = 4
    # main menu
    [[menu.main]]
    name = "Slash"
    parent = "Guitarristas"
    URL = "slash/"
    weight = 5

  # footer menu
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "mapa-web"
  weight = 1
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/comprar-una-guitarra.png"
home = "Inicio"
# Meta data
description = "¿Quieres aprender a tocar la guitarra en 2020 ? Encuentra consejos, comparativas y ayuda para comprar una guitarra"
author = "Comprar una Guitarra"
# Google Analitycs
#googleAnalitycsID = "UA-167226734-1"
# copyright
copyright = "| copyright &copy; 2020 [Comprar una Guitarra](/) All Rights Reserved |"