######################## default configuration ####################
baseURL = "https://www.comoinvertirenbolsa.top/"
languageCode = "es"
title = "Todo lo que necesitas saber para invertir en bolsa"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/cookie-consent-box/cookie-consent-box.min.js"
  [[params.plugins.js]]
  URL = "plugins/lazy-youtube-embed/lazy-youtube-embed.js"

############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Introducción a la bolsa"
  URL = "/introduccion-bolsa"
  weight = 1

  # main menu
  [[menu.main]]
  name = "Análisis Técnico"
  URL = "/analisis-tecnico"
  weight = 2
    
   # main menu
  [[menu.main]]
  name = "Trading"
  URL = "/trading"
  weight = 3
    
  # main menu
  [[menu.main]]
  name = "Educación Financiera"
  URL = "/educacion-financiera"
  weight = 4

  # main menu
    [[menu.main]]
    name = "Blog"
    URL = "/blog"
    weight = 5

  # footer menu
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "mapa-web"
  weight = 1
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/logo-image.png"
home = "Inicio"
# Meta data
description = "El portal donde podrás conocer todo acerca de cómo empezar a invertir en bolsa desde cero"
author = "ComoInvertirEnBolsa"
# Google Analitycs
googleAnalitycsID = "G-HCWHTPRTY7"
# copyright
copyright = "| Copyright (c) 2020 Themefisher |"

# Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 60


############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/chollosbolsa"