######################## default configuration ####################
baseURL = "https://www.comprarunaguitarra.com/"
languageCode = "es"
title = "Consejos y reviews sobre que guitarra comprar en 2021"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/cookie-consent-box/cookie-consent-box.min.js"
  [[params.plugins.js]]
  URL = "plugins/lazy-youtube-embed/lazy-youtube-embed.js"

############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Las mejores"
  URL = "/categories/listas-top"
  weight = 1

  # main menu
  [[menu.main]]
  name = "Marcas"
  URL = "/categories/reviews"
  weight = 2
    
   # main menu
  [[menu.main]]
  name = "Accesorios"
  URL = "/categories/accesorios"
  weight = 3
    
  # main menu
  [[menu.main]]
  name = "Guitarristas"
  URL = "/categories/guitarristas"
  weight = 4

  [[menu.main]]
  name = "Blog"
  URL = "/blog"
  weight = 5

  # footer menu
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "mapa-web"
  weight = 1
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/comprar-una-guitarra.png"
home = "Inicio"
# Meta data
description = "Aquí podrás encontrar reviews, comparativas, consejos, tutoriales y noticias acerca del mundo de la guitarra y otros accesorios relacionados con la música"
author = "CuG"
# Google Analitycs
googleAnalitycsID = "UA-167226734-1"
# copyright
copyright = "| Copyright (c) 2020 Themefisher |"

# Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 60


############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/ComprarUna"