######################## default configuration ####################
baseURL = "https://www.comprarunaguitarra.com/"
languageCode = "es-ES"
title = "Consejos y reviews sobre que guitarra comprar en 2020"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Guitarras"
  hasChildren = true
  weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras baratas"
    parent = "Guitarras"
    URL = "guitarras-baratas/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras eléctricas para niños"
    parent = "Guitarras"
    URL = "guitarras-para-ninos/"
    weight = 2
    [[menu.main]]
    name = "Guitarras pequeñas y ukeleles"
    parent = "Guitarras"
    URL = "guitarra-ukelele/"
    weight = 3

  # main menu
  [[menu.main]]
  name = "Marcas"
  hasChildren = true
  weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Yamaha"
    parent = "Marcas"
    URL = "guitarras-yamaha/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Guitarras LTD ESP"
    parent = "Marcas"
    URL = "guitarras-ltd/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Guitarras Squier"
    parent = "Marcas"
    URL = "guitarras-squier/"
    weight = 3
    # main menu
    [[menu.main]]
    name = "Guitarras Cort"
    parent = "Marcas"
    URL = "guitarras-cort/"
    weight = 4

  # main menu
  [[menu.main]]
  name = "Accesorios"
  hasChildren = true
  weight = 3
    # main menu
    [[menu.main]]
    name = "Behringer Guitar Link"
    parent = "Accesorios"
    URL = "behringer-guitar-link/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Inlays para guitarra"
    parent = "Accesorios"
    URL = "inlays-guitarra/"
    weight = 1
    # main menu
    [[menu.main]]
    name = "Puas de guitarra"
    parent = "Accesorios"
    URL = "puas-guitarra/"
    weight = 2
    # main menu
    [[menu.main]]
    name = "Transmisores inalámbricos"
    parent = "Accesorios"
    URL = "transmisores-inalambricos-guitarra/"
    weight = 3

  # main menu
    [[menu.main]]
    name = "Guitarristas"
    hasChildren = true
    weight = 4
    # main menu
    [[menu.main]]
    name = "James Hetfield"
    parent = "Guitarristas"
    URL = "james-hetfield/"
    weight = 1

  # footer menu
  [[menu.footer]]
  name = "Aviso legal"
  URL = "aviso-legal"
  weight = 1
  
  [[menu.footer]]
  name = "Política de privacidad"
  URL = "politica-de-privacidad"
  weight = 2

  [[menu.footer]]
  name = "Uso de cookies"
  URL = "uso-de-cookies"
  weight = 3
  [[menu.footer]]
  name = "Mapa del sitio web"
  URL = "mapa-web"
  weight = 4
  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo_web_opt_2.png"
home = "Inicio"
# Meta data
description = "¿Quieres aprender a tocar la guitarra en 2020 ? Encuentra consejos, comparativas y ayuda para comprar una guitarra"
author = "Comprar una Guitarra"
# Google Analitycs
googleAnalitycsID = "UA-167226734-1"
# copyright
copyright = "| copyright &copy; 2020 [Comprar una Guitarra](/) All Rights Reserved |"